sequenceDiagram
    participant User
    participant Restaurant
    Note left of User: scan qr code
    Note left of User: queuing with <br/>the ticket number
    Note right of Restaurant: Restaurant will assign <br/> the table to the<br/> ticket number
    Note left of User: user can place order <br/> after table assigned
    Note left of User: user can check the<br/> order page & bill page
    Note left of User: user finish meal and<br/> pay at the cashier
