%% レストランユーザー流れ - 2 (メニュー管理/ランディングページ), slide 22
%% Restaurant user flow-2 (Menu management / Landing page)

graph TD
  A1(admin'manage' page) --> |click food configuration|B(food page appears)
  B-->|click 編集|C(green food detail dialogue box appears)
  C-->|update dialogue box|D(dialogue food detail updated)
  D-->|insert food picture|E(dialogue food picture updated)
  E-->|click 編集|F(food detail updated, dialogue close)
