%% ユーザー流れ - 1 (利用規約/ランディングページ)の改善, slide 21
%% Restaurant user flow-2 (Menu management / Landing page)

graph TD
  A1(admin'manage') --> |click category configuration|B(category page appears)
  B-->|click Create New Category|C(input box to ask category name)
  C-->|click create|D(new category created)
  D-->E(New category dialogue hide)
  E-->F(Item found in category index page)
