%% ユーザー流れ - 5 (カートの確認)(席案内済んだ場合), slide 10
%% User flow -5 (Check cart) (If seat guidance has been completed)

graph TD
  A1(main page with 番號 only) --> |user click bottom red bar|B(ordered food list shown)
  B-->|user change item number|C(Quantity updated)
  C-->|user click upper left close button|A2
