name: self_test_helloworld
on:
  push:
    branches:
      - test/self-test/**

jobs:
  UI_test_functional:
    runs-on: ubuntu-20.04
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - run: |
          hostname
