name: self_test_helloworld
on:
  push:
    branches:
      - test/test_TID_033/helloworld

jobs:
  UI_test_functional:
    runs-on: ubuntu-20.04
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - run: |
          cd $GITHUB_WORKSPACE/_ref/docker-selenium
            docker-compose -f docker-compose-v3.yml up -d  --scale chrome_1=10
            echo 'sleep a while to let docker steady'
            sleep 30

            docker-compose -f docker-compose-v3.yml ps
          cd $GITHUB_WORKSPACE

      - name: prepare ubuntu
        env: # Or as an environment variable
          SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
        run: |
          sudo apt update
          sudo apt install -y python3 python3-pip python3-dev python3-wheel python3-setuptools
          python3 -V
          python3 -m pip install pipenv

      - name: run test
        env: # Or as an environment variable
          SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
        run: |
          export PYTHON_BIN_PATH="$(python3 -m site --user-base)/bin"
          export PATH="$PATH:$PYTHON_BIN_PATH"

          export LC_ALL=C.UTF-8
          export LANG=C.UTF-8
          pipenv install pytest pytest-html
          pipenv run pytest \
            --maxfail=999 \
            --json-report \
            --html=reports/functional/index.html \
            -x tests/UI_test/functional/smoke_test_remote_parallel/test_TID_033.py

      - uses: actions/upload-artifact@v2
        with:
          name: actual-screen-shot
          path: tests/UI_test/functional/smoke_test_remote_parallel/actual
          retention-days: 1
        if: always()

      - name: action-upload-artifact-tryout
        uses: actions/upload-artifact@v2
        with:
          name: 'reports_functional'
          path: reports/functional
          retention-days: 1
        if: always()
