%% ユーザー流れ - 6 (注文確認/会計)(注文がない場合), slide 11
%% User flow-6 (order confirmation / accounting) (if there is no order)

graph TD
  A1(main page with 番號 only) --> |user tap upper right green button番號|B(booking detail page show)
  B-->|user click upper left close button|C(booking detail on admin panel no changed)
  C-->D(main page shown)
